version: '3.7'

services:
  minio:
    image: quay.io/minio/minio
    environment:
      - MINIO_ROOT_USER=newMinioAdmin
      - MINIO_ROOT_PASSWORD=newMinioPassword
      - MINIO_VOLUMES="/data{1...4}"
    command: minio server /data1 /data2 /data3 /data4 --console-address :9090
    ports:
      - '9004:9000'
      - '9095:9090'
    volumes:
      - data1:/data1
      - data2:/data2
      - data3:/data3
      - data4:/data4
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  data1:
  data2:
  data3:
  data4:
